DATA C2_2_paractice ;
SET TRAINING.NPS200 (FIRSTOBS=21 OBS=50) ;
KEEP SPEC_ID_SNO JID RECU_FR_DD RECU_T0_DD ;
RUN;

PROC CONTENTS DATA=TRAINING.NPS200;
RUN;

PROC CONTENTS DATA=TRAINING.NPS200
ORDER = VARNUM;
RUN;

DATA C3_1_MALE;
SET TRAINING.NPS200;
IF SEX_TP_CD='1';
RUN;

DATA C3_1_FEMALE_GT60;
SET TRAINING.NPS200;
IF SEX_TP_CD='2' AND AGG IN ('13','14','15','16');
RUN;

DATA C3_1_FOM ; 
SET TRAINING.NPS200;
IF FOM_TP_CD = '021' THEN NEW_FOM_CD=1;
ELSE NEW_FOM_CD=2;
RUN;

DATA C3_2_RESP;
SET TRANING.NPS200;
IF SUBSTR(MSICK_CD,1,1)='J' THEN RESP_YN=1 ;
ELSE RESP_YN=0;
RUN;

DATA C3_2_RESP2;
SET TRANING.NPS200;
IF SUBSTR(SICK_CE,1,1)='J' AND SICK_SNO <=3 THEN RESP_YN =1;
ELSE RESP_YN=0;
RUN;

PROC SORT DATA = C2_2_PRACTICE OUT= C3_3_MERGE1;
BY SPEC_ID_SNO;
RUN;

PROC SORT DATA = TRAINING.NPS400 OUT= C3_3_MERGE2;
BY SPEC_ID_SNO;
RUN;

DATA C3_3_MERGE;
MERGE C3_3_MERGE1(IN=A) C3_3_MERGE2(IN=B);
BY SPEC_ID_SNO;
IF A;
RUN;

PROC SORT DATA = TRAINING.NPS200 
OUT=C3_4_NODUPKEY (KEEP=JID) NODUPKEY;
BY JID;
RUN;

PROC FREQ DATA=TRAINING.NPS200;
TABLES SEX_TP_CD INSUF_TF_CD;
TABLES SEX_TP_CE*INSUF_TF_CD;
RUN;


/*예제1*/
DATA C4_EX1;
SET TRAINING.NPS200;
IF SUBSTR(MSICK_CD,1,3) IN ('J45','J46') THEN ASTHMA=1;
ELSE ASTHMA = 0;
RUN;

DATA C4_EX2;
SET C4_EX1;
WHERE ASTHMA=1;
RUN;

PROC FREQ DATA=C4_EX2;
TABLES SEX_TP_CD;
RUN;


/*예제2*/
PROC FREQ DATA=C4_EX2;
TABLES SEX_TP_CD DGSBJT_CD SEX_TP_CD*DGSBJT_CD;
RUN;


/*예제3*/
DATA C4_EX3;
SET C4_EX1;
MON = MONTH(RECU_FR_DD);
WHERE ASTHMA=1;
RUN;

PROC FREQ DATA=C4_EX3;
TABLES MON*SEX_TP_CE*DGSBJT_CD;
RUN;














 


